






# Installation et chargement des packages nécessaires
install.packages(c("foreign", "stargazer"), type = "binary")
library(foreign)
library(stargazer)

# Question 1 : Importation et exportation des données
mydata <- read.dta("https://dss.princeton.edu/training/Panel101.dta")
write.table(mydata, file = "mydata.csv", sep = ";")

# Question 2 : Régression linéaire
reg <- lm(x3 ~ x1 + x2, data = mydata)
summary(reg)

# Question bonus : x2 en interaction avec opinion
reg2 <- lm(x3 ~ x2 * opinion, data = mydata)
summary(reg2)

# Régression logistique
logit <- glm(y_bin ~ x1 + x2 + x3, family = binomial(link = "logit"), data = mydata)
summary(logit)
stargazer(logit, type = "html", out = "logitM1.htm")

# Question 5 : Prédiction avec les moyennes
x1 <- mean(mydata$x1)
x2 <- mean(mydata$x2)
x3 <- mean(mydata$x3)

allmean <- data.frame(x1 = x1, x2 = x2, x3 = x3)
allmean$pred.prob <- predict(logit, newdata = allmean, type = "response")
print(allmean)

# Question 6 : Modèle avec variable catégorielle
model_4 <- glm(y_bin ~ x1 + x2 + x3 + opinion, family = binomial(link = "logit"), data = mydata)
summary(model_4)
stargazer(model_4, type = "html", out = "resultats_model_4.doc")

exp(model_4$coefficients)
<<<<<<< HEAD

# Question 7 : Probabilités pour différentes opinions
opinions <- c("Agree", "str disag", " Disag")
results <- data.frame()
=======
#ou 
logitor(y_bin~ x1 + x2 +x3 relevel(opinion, ref="Agree"), data=mydata) # Logitor permet de mettre en Odds Ratio 

```



```{r}
# Question 7 : Quelle est la probabilité que y soit égal à 1 ? (Astuce : Il n'est pas possible d'estimer la moyenne d'une variable catégorielle, mais on peut calculer la proba que y = 1 pour chaque cas, ex : Estimer la proba que y= 1 lorsque opinion = "Agree" etc)
allmean=data.frame(x1, x2, x3, opinion= as.factor(c("Agree")))
allmean$pred.prob=predict(logit, newdata = allmean, type="response")
allmean=data.frame(x1, x2, x3, opinion= as.factor(c("str disag")))
allmean$pred.prob=predict(logit, newdata = allmean, type="response")
allmean=data.frame(x1, x2, x3, opinion= as.factor(c(" Disag")))
allmean$pred.prob=predict(logit, newdata = allmean, type="response")
```
#  Partie 2 : Var catégorielle ordonnée ( juste les interpretations ) 

X1 : 2.668 lorsque X1 augmente de 1 alors cela augmente la proba de passer a une actegorie supérieur est multiplié par 2, 668% ou augmente de 2, 66 % . 
Donc le coef est significatif 
2- Quelles sont les proba prédit de Y ? 
Le nombre de la ligne Mean  sont les prob prédites de chaque 
ml.pred =predict(ml, type="probs")
summary(ml.predict)

# Partie 3 : Var catégorielle non -Ordonnée



>>>>>>> 9e726f4edfbbe782fa6b37286a8b2238b405610a

for (op in opinions) {
  allmean <- data.frame(x1 = x1, x2 = x2, x3 = x3, opinion = factor(op))
  allmean$pred.prob <- predict(model_4, newdata = allmean, type = "response")
  results <- rbind(results, allmean)
}

print(results)